@startuml

title Restore Logic \n

start

:retrive vault inventory;
:read inventory (by date);

while (more items?) is (yes)
    :download;
    if (file already exist?) then (yes)
        :move old file to date folder;
    else (no) 
        ' next step (nothing to do)
    endif
    :save file (use description as path);
endwhile (no)

end

@enduml
